
appconfig:
#    http_proxy: proxy3.bj.petrochina:8080
    data_dir_path: d://wx//data
    list:
        - name: my another name
          description: my description
        - name: my another name
          description: my description

spring:
    devtools:
        restart:
            enabled: false 
    h2:
        console:
            enabled: false
            settings.web-allow-others: true
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:tcp://localhost:9092/d:/db/h2/wx
        username: test
        password: test
    freemarker:
        expose-request-attributes: true
        expose-session-attributes: true
        expose-spring-macro-helpers: true
        request-context-attribute: request
        settings: 
            classic_compatible: true
    jpa:
        properties:
            hibernate:
                hbm2ddl.auto: update #create update none
                show_sql: true
                format_sql: true

security:
    basic:
        enabled: false
        authorize-mode: NONE

server:
    port: 80
    #context-path: /wxctrl


   