
appconfig:
    name: sb-ms-custdepl
    version: 0.1-CUSTOMER
    list:
        - name: my another name
          description: my description
        - name: my another name
          description: my description

spring:
    application:
        name: cruncher
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:tcp://localhost:9092/d:/db/h2/test
        username: test
        password: test
    freemarker:
        settings: 
            classic_compatible: true
    jpa:
        properties:
            hibernate:
                hbm2ddl.auto: update
                show_sql: true
                format_sql: true

logging:
    level:
        org:
            hibernate: INFO

security:
    basic:
        enabled: false
    user:
        name: test
        password: 123

server:
    port: 80
    #contextPath: /
   